[package]
name = "my_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
obfuscator = { path = "../obfuscator" }
zeroize = "1.5"
crc32fast = "1.3"
base85 = "2.0"
base45 = "3.1.0"
base36 = "0.0.1"
base91 = "0.1.0"
base122-rs = "0.1.4"
bs58 = "0.5.0"
