/**
 * exe_to_embedded_loader.c
 *
 * Compilation: gcc exe_to_embedded_loader.c -o exe_to_embedded_loader
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#ifdef _WIN32
#include <windows.h>
#else
typedef uint32_t DWORD;
typedef uint16_t WORD;
typedef uint8_t BYTE;
typedef uint64_t ULONG_PTR;
typedef uint64_t SIZE_T;

#pragma pack(push, 1)
typedef struct _IMAGE_DOS_HEADER {
    WORD e_magic;
    WORD e_cblp;
    WORD e_cp;
    WORD e_crlc;
    WORD e_cparhdr;
    WORD e_minalloc;
    WORD e_maxalloc;
    WORD e_ss;
    WORD e_sp;
    WORD e_csum;
    WORD e_ip;
    WORD e_cs;
    WORD e_lfarlc;
    WORD e_ovno;
    WORD e_res[4];
    WORD e_oemid;
    WORD e_oeminfo;
    WORD e_res2[10];
    int32_t e_lfanew;
} IMAGE_DOS_HEADER, *PIMAGE_DOS_HEADER;

typedef struct _IMAGE_FILE_HEADER {
    WORD Machine;
    WORD NumberOfSections;
    DWORD TimeDateStamp;
    DWORD PointerToSymbolTable;
    DWORD NumberOfSymbols;
    WORD SizeOfOptionalHeader;
    WORD Characteristics;
} IMAGE_FILE_HEADER, *PIMAGE_FILE_HEADER;

typedef struct _IMAGE_DATA_DIRECTORY {
    DWORD VirtualAddress;
    DWORD Size;
} IMAGE_DATA_DIRECTORY, *PIMAGE_DATA_DIRECTORY;

typedef struct _IMAGE_OPTIONAL_HEADER64 {
    WORD Magic;
    BYTE MajorLinkerVersion;
    BYTE MinorLinkerVersion;
    DWORD SizeOfCode;
    DWORD SizeOfInitializedData;
    DWORD SizeOfUninitializedData;
    DWORD AddressOfEntryPoint;
    DWORD BaseOfCode;
    ULONG_PTR ImageBase;
    DWORD SectionAlignment;
    DWORD FileAlignment;
    WORD MajorOperatingSystemVersion;
    WORD MinorOperatingSystemVersion;
    WORD MajorImageVersion;
    WORD MinorImageVersion;
    WORD MajorSubsystemVersion;
    WORD MinorSubsystemVersion;
    DWORD Win32VersionValue;
    DWORD SizeOfImage;
    DWORD SizeOfHeaders;
    DWORD CheckSum;
    WORD Subsystem;
    WORD DllCharacteristics;
    ULONG_PTR SizeOfStackReserve;
    ULONG_PTR SizeOfStackCommit;
    ULONG_PTR SizeOfHeapReserve;
    ULONG_PTR SizeOfHeapCommit;
    DWORD LoaderFlags;
    DWORD NumberOfRvaAndSizes;
    IMAGE_DATA_DIRECTORY DataDirectory[16];
} IMAGE_OPTIONAL_HEADER64, *PIMAGE_OPTIONAL_HEADER64;

typedef struct _IMAGE_NT_HEADERS64 {
    DWORD Signature;
    IMAGE_FILE_HEADER FileHeader;
    IMAGE_OPTIONAL_HEADER64 OptionalHeader;
} IMAGE_NT_HEADERS64, *PIMAGE_NT_HEADERS64;

typedef struct _IMAGE_SECTION_HEADER {
    BYTE Name[8];
    union {
        DWORD PhysicalAddress;
        DWORD VirtualSize;
    } Misc;
    DWORD VirtualAddress;
    DWORD SizeOfRawData;
    DWORD PointerToRawData;
    DWORD PointerToRelocations;
    DWORD PointerToLinenumbers;
    WORD NumberOfRelocations;
    WORD NumberOfLinenumbers;
    DWORD Characteristics;
} IMAGE_SECTION_HEADER, *PIMAGE_SECTION_HEADER;
#pragma pack(pop)
#endif

const char* default_template =
    "/**\n"
    " * loader_template.c - Advanced Reflective Loader (Zero Dependencies)\n"
    " * Optimized for Rust and modern Windows environments.\n"
    " */\n"
    "\n"
    "#define NULL ((void*)0)\n"
    "\n"
    "#ifdef _WIN64\n"
    "typedef unsigned long long QWORD;\n"
    "typedef unsigned long long ULONG_PTR;\n"
    "typedef unsigned long long UINT_PTR;\n"
    "#else\n"
    "typedef unsigned int QWORD;\n"
    "typedef unsigned int ULONG_PTR;\n"
    "typedef unsigned int UINT_PTR;\n"
    "#endif\n"
    "\n"
    "typedef unsigned int DWORD;\n"
    "typedef unsigned short WORD;\n"
    "typedef unsigned char BYTE;\n"
    "typedef void* PVOID;\n"
    "typedef PVOID HANDLE;\n"
    "typedef PVOID HMODULE;\n"
    "typedef PVOID HINSTANCE;\n"
    "typedef QWORD SIZE_T;\n"
    "typedef int BOOL;\n"
    "typedef long LONG;\n"
    "typedef unsigned long ULONG;\n"
    "typedef void VOID;\n"
    "typedef ULONG* PULONG;\n"
    "typedef unsigned short USHORT;\n"
    "typedef USHORT* PWSTR;\n"
    "typedef char* PSTR;\n"
    "typedef USHORT WCHAR;\n"
    "typedef unsigned char BOOLEAN;\n"
    "typedef void* LPVOID;\n"
    "typedef unsigned long long DWORD64;\n"
    "typedef DWORD* PDWORD;\n"
    "typedef WORD* PWORD;\n"
    "typedef LONG NTSTATUS;\n"
    "typedef DWORD* LPDWORD;\n"
    "\n"
    "#define TRUE 1\n"
    "#define FALSE 0\n"
    "\n"
    "#define DLL_PROCESS_ATTACH 1\n"
    "#define DLL_THREAD_ATTACH  2\n"
    "#define DLL_THREAD_DETACH  3\n"
    "#define DLL_PROCESS_DETACH 0\n"
    "\n"
    "#define MEM_COMMIT 0x00001000\n"
    "#define MEM_RESERVE 0x00002000\n"
    "#define MEM_RELEASE 0x00008000\n"
    "#define PAGE_READWRITE 0x04\n"
    "#define PAGE_EXECUTE_READWRITE 0x40\n"
    "#define PAGE_EXECUTE_READ 0x20\n"
    "#define PAGE_EXECUTE 0x10\n"
    "#define PAGE_READONLY 0x02\n"
    "#define PAGE_NOACCESS 0x01\n"
    "\n"
    "#define IMAGE_DIRECTORY_ENTRY_EXPORT 0\n"
    "#define IMAGE_DIRECTORY_ENTRY_IMPORT 1\n"
    "#define IMAGE_DIRECTORY_ENTRY_EXCEPTION 3\n"
    "#define IMAGE_DIRECTORY_ENTRY_BASERELOC 5\n"
    "#define IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG 10\n"
    "#define IMAGE_DIRECTORY_ENTRY_TLS 9\n"
    "#define IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT 13\n"
    "\n"
    "#define IMAGE_FILE_DLL 0x2000\n"
    "\n"
    "#define IMAGE_SCN_MEM_EXECUTE 0x20000000\n"
    "#define IMAGE_SCN_MEM_READ 0x40000000\n"
    "#define IMAGE_SCN_MEM_WRITE 0x80000000\n"
    "\n"
    "#define IMAGE_REL_BASED_HIGHLOW 3\n"
    "#define IMAGE_REL_BASED_DIR64 10\n"
    "\n"
    "#ifdef _WIN64\n"
    "#define IMAGE_ORDINAL_FLAG 0x8000000000000000ULL\n"
    "#else\n"
    "#define IMAGE_ORDINAL_FLAG 0x80000000\n"
    "#endif\n"
    "\n"
    "#define IMAGE_SNAP_BY_ORDINAL(Ordinal) ((Ordinal & IMAGE_ORDINAL_FLAG) != 0)\n"
    "#define IMAGE_ORDINAL(Ordinal) (Ordinal & 0xffff)\n"
    "\n"
    "#ifndef MAX_PATH\n"
    "#define MAX_PATH 260\n"
    "#endif\n"
    "\n"
    "#ifdef _WIN64\n"
    "#define WINABI\n"
    "#else\n"
    "#define WINABI __attribute__((stdcall))\n"
    "#endif\n"
    "\n"
    "#ifdef _WIN64\n"
    "#ifndef _MSC_VER\n"
    "__asm__(\n"
    "    \".global call_aligned\\n\"\n"
    "    \"call_aligned:\\n\"\n"
    "    \"push %rbp\\n\"\n"
    "    \"mov %rsp, %rbp\\n\"\n"
    "    \"and $-16, %rsp\\n\"\n"
    "    \"sub $48, %rsp\\n\"\n"
    "    \"mov %rcx, %rax\\n\"        // RAX = func\n"
    "    \"mov %rdx, %rcx\\n\"        // RCX = p1\n"
    "    \"mov %r8, %rdx\\n\"         // RDX = p2\n"
    "    \"mov %r9, %r8\\n\"          // R8  = p3\n"
    "    \"mov 48(%rbp), %r9\\n\"     // R9  = p4\n"
    "    \"call *%rax\\n\"\n"
    "    \"mov %rbp, %rsp\\n\"\n"
    "    \"pop %rbp\\n\"\n"
    "    \"ret\\n\"\n"
    ");\n"
    "extern ULONG_PTR call_aligned(PVOID func, PVOID p1, PVOID p2, PVOID p3, PVOID p4);\n"
    "#endif\n"
    "#endif\n"
    "\n"
    "// --- Structures ---\n"
    "\n"
    "typedef struct _UNICODE_STRING {\n"
    "    USHORT Length;\n"
    "    USHORT MaximumLength;\n"
    "    PWSTR  Buffer;\n"
    "} UNICODE_STRING, *PUNICODE_STRING;\n"
    "\n"
    "typedef struct _ANSI_STRING {\n"
    "    USHORT Length;\n"
    "    USHORT MaximumLength;\n"
    "    PSTR   Buffer;\n"
    "} ANSI_STRING, *PANSI_STRING;\n"
    "\n"
    "typedef struct _LIST_ENTRY {\n"
    "    struct _LIST_ENTRY *Flink;\n"
    "    struct _LIST_ENTRY *Blink;\n"
    "} LIST_ENTRY, *PLIST_ENTRY;\n"
    "\n"
    "typedef struct _PEB_LDR_DATA {\n"
    "    ULONG Length;\n"
    "    BOOLEAN Initialized;\n"
    "    HANDLE SsHandle;\n"
    "    LIST_ENTRY InLoadOrderModuleList;\n"
    "    LIST_ENTRY InMemoryOrderModuleList;\n"
    "    LIST_ENTRY InInitializationOrderModuleList;\n"
    "} PEB_LDR_DATA, *PPEB_LDR_DATA;\n"
    "\n"
    "typedef struct _LDR_DATA_TABLE_ENTRY {\n"
    "    LIST_ENTRY InLoadOrderLinks;\n"
    "    LIST_ENTRY InMemoryOrderLinks;\n"
    "    LIST_ENTRY InInitializationOrderLinks;\n"
    "    PVOID DllBase;\n"
    "    PVOID EntryPoint;\n"
    "    ULONG SizeOfImage;\n"
    "    UNICODE_STRING FullDllName;\n"
    "    UNICODE_STRING BaseDllName;\n"
    "} LDR_DATA_TABLE_ENTRY, *PLDR_DATA_TABLE_ENTRY;\n"
    "\n"
    "typedef struct _PEB {\n"
    "    BOOLEAN InheritedAddressSpace;\n"
    "    BOOLEAN ReadImageFileExecOptions;\n"
    "    BOOLEAN BeingDebugged;\n"
    "    union {\n"
    "        BOOLEAN BitField;\n"
    "        struct {\n"
    "            BOOLEAN ImageUsesLargePages : 1;\n"
    "            BOOLEAN IsProtectedProcess : 1;\n"
    "            BOOLEAN IsImageDynamicallyRelocated : 1;\n"
    "            BOOLEAN SkipPatchingLocals : 1;\n"
    "            BOOLEAN IsPackagedProcess : 1;\n"
    "            BOOLEAN IsAppContainer : 1;\n"
    "            BOOLEAN IsProtectedProcessLight : 1;\n"
    "            BOOLEAN IsLongPathAwareProcess : 1;\n"
    "        };\n"
    "    };\n"
    "    HANDLE Mutant;\n"
    "    PVOID ImageBaseAddress;\n"
    "    PPEB_LDR_DATA Ldr;\n"
    "} PEB, *PPEB;\n"
    "\n"
    "typedef struct _IMAGE_DOS_HEADER {\n"
    "    WORD e_magic;\n"
    "    WORD e_cblp;\n"
    "    WORD e_cp;\n"
    "    WORD e_crlc;\n"
    "    WORD e_cparhdr;\n"
    "    WORD e_minalloc;\n"
    "    WORD e_maxalloc;\n"
    "    WORD e_ss;\n"
    "    WORD e_sp;\n"
    "    WORD e_csum;\n"
    "    WORD e_ip;\n"
    "    WORD e_cs;\n"
    "    WORD e_lfarlc;\n"
    "    WORD e_ovno;\n"
    "    WORD e_res[4];\n"
    "    WORD e_oemid;\n"
    "    WORD e_oeminfo;\n"
    "    WORD e_res2[10];\n"
    "    LONG e_lfanew;\n"
    "} IMAGE_DOS_HEADER, *PIMAGE_DOS_HEADER;\n"
    "\n"
    "typedef struct _IMAGE_FILE_HEADER {\n"
    "    WORD Machine;\n"
    "    WORD NumberOfSections;\n"
    "    DWORD TimeDateStamp;\n"
    "    DWORD PointerToSymbolTable;\n"
    "    DWORD NumberOfSymbols;\n"
    "    WORD SizeOfOptionalHeader;\n"
    "    WORD Characteristics;\n"
    "} IMAGE_FILE_HEADER, *PIMAGE_FILE_HEADER;\n"
    "\n"
    "typedef struct _IMAGE_DATA_DIRECTORY {\n"
    "    DWORD VirtualAddress;\n"
    "    DWORD Size;\n"
    "} IMAGE_DATA_DIRECTORY, *PIMAGE_DATA_DIRECTORY;\n"
    "\n"
    "#ifdef _WIN64\n"
    "typedef struct _IMAGE_OPTIONAL_HEADER64 {\n"
    "    WORD Magic;\n"
    "    BYTE MajorLinkerVersion;\n"
    "    BYTE MinorLinkerVersion;\n"
    "    DWORD SizeOfCode;\n"
    "    DWORD SizeOfInitializedData;\n"
    "    DWORD SizeOfUninitializedData;\n"
    "    DWORD AddressOfEntryPoint;\n"
    "    DWORD BaseOfCode;\n"
    "    ULONG_PTR ImageBase;\n"
    "    DWORD SectionAlignment;\n"
    "    DWORD FileAlignment;\n"
    "    WORD MajorOperatingSystemVersion;\n"
    "    WORD MinorOperatingSystemVersion;\n"
    "    WORD MajorImageVersion;\n"
    "    WORD MinorImageVersion;\n"
    "    WORD MajorSubsystemVersion;\n"
    "    WORD MinorSubsystemVersion;\n"
    "    DWORD Win32VersionValue;\n"
    "    DWORD SizeOfImage;\n"
    "    DWORD SizeOfHeaders;\n"
    "    DWORD CheckSum;\n"
    "    WORD Subsystem;\n"
    "    WORD DllCharacteristics;\n"
    "    ULONG_PTR SizeOfStackReserve;\n"
    "    ULONG_PTR SizeOfStackCommit;\n"
    "    ULONG_PTR SizeOfHeapReserve;\n"
    "    ULONG_PTR SizeOfHeapCommit;\n"
    "    DWORD LoaderFlags;\n"
    "    DWORD NumberOfRvaAndSizes;\n"
    "    IMAGE_DATA_DIRECTORY DataDirectory[16];\n"
    "} IMAGE_OPTIONAL_HEADER64, *PIMAGE_OPTIONAL_HEADER64;\n"
    "typedef IMAGE_OPTIONAL_HEADER64 IMAGE_OPTIONAL_HEADER;\n"
    "#else\n"
    "typedef struct _IMAGE_OPTIONAL_HEADER32 {\n"
    "    WORD Magic;\n"
    "    BYTE MajorLinkerVersion;\n"
    "    BYTE MinorLinkerVersion;\n"
    "    DWORD SizeOfCode;\n"
    "    DWORD SizeOfInitializedData;\n"
    "    DWORD SizeOfUninitializedData;\n"
    "    DWORD AddressOfEntryPoint;\n"
    "    DWORD BaseOfCode;\n"
    "    DWORD ImageBase;\n"
    "    DWORD SectionAlignment;\n"
    "    DWORD FileAlignment;\n"
    "    WORD MajorOperatingSystemVersion;\n"
    "    WORD MinorOperatingSystemVersion;\n"
    "    WORD MajorImageVersion;\n"
    "    WORD MinorImageVersion;\n"
    "    WORD MajorSubsystemVersion;\n"
    "    WORD MinorSubsystemVersion;\n"
    "    DWORD Win32VersionValue;\n"
    "    DWORD SizeOfImage;\n"
    "    DWORD SizeOfHeaders;\n"
    "    DWORD CheckSum;\n"
    "    WORD Subsystem;\n"
    "    WORD DllCharacteristics;\n"
    "    DWORD SizeOfStackReserve;\n"
    "    DWORD SizeOfStackCommit;\n"
    "    DWORD SizeOfHeapReserve;\n"
    "    DWORD SizeOfHeapCommit;\n"
    "    DWORD LoaderFlags;\n"
    "    DWORD NumberOfRvaAndSizes;\n"
    "    IMAGE_DATA_DIRECTORY DataDirectory[16];\n"
    "} IMAGE_OPTIONAL_HEADER32, *PIMAGE_OPTIONAL_HEADER32;\n"
    "typedef IMAGE_OPTIONAL_HEADER32 IMAGE_OPTIONAL_HEADER;\n"
    "#endif\n"
    "\n"
    "typedef struct _IMAGE_NT_HEADERS {\n"
    "    DWORD Signature;\n"
    "    IMAGE_FILE_HEADER FileHeader;\n"
    "    IMAGE_OPTIONAL_HEADER OptionalHeader;\n"
    "} IMAGE_NT_HEADERS, *PIMAGE_NT_HEADERS;\n"
    "\n"
    "typedef struct _IMAGE_SECTION_HEADER {\n"
    "    BYTE Name[8];\n"
    "    union {\n"
    "        DWORD PhysicalAddress;\n"
    "        DWORD VirtualSize;\n"
    "    } Misc;\n"
    "    DWORD VirtualAddress;\n"
    "    DWORD SizeOfRawData;\n"
    "    DWORD PointerToRawData;\n"
    "    DWORD PointerToRelocations;\n"
    "    DWORD PointerToLinenumbers;\n"
    "    WORD NumberOfRelocations;\n"
    "    WORD NumberOfLinenumbers;\n"
    "    DWORD Characteristics;\n"
    "} IMAGE_SECTION_HEADER, *PIMAGE_SECTION_HEADER;\n"
    "\n"
    "#define IMAGE_FIRST_SECTION(ntheader) ((PIMAGE_SECTION_HEADER)((ULONG_PTR)(ntheader) + \\\n"
    "    sizeof(DWORD) + sizeof(IMAGE_FILE_HEADER) + (ntheader)->FileHeader.SizeOfOptionalHeader))\n"
    "\n"
    "typedef struct _IMAGE_EXPORT_DIRECTORY {\n"
    "    DWORD Characteristics;\n"
    "    DWORD TimeDateStamp;\n"
    "    WORD MajorVersion;\n"
    "    WORD MinorVersion;\n"
    "    DWORD Name;\n"
    "    DWORD Base;\n"
    "    DWORD NumberOfFunctions;\n"
    "    DWORD NumberOfNames;\n"
    "    DWORD AddressOfFunctions;\n"
    "    DWORD AddressOfNames;\n"
    "    DWORD AddressOfNameOrdinals;\n"
    "} IMAGE_EXPORT_DIRECTORY, *PIMAGE_EXPORT_DIRECTORY;\n"
    "\n"
    "typedef struct _IMAGE_IMPORT_DESCRIPTOR {\n"
    "    union {\n"
    "        DWORD Characteristics;\n"
    "        DWORD OriginalFirstThunk;\n"
    "    };\n"
    "    DWORD TimeDateStamp;\n"
    "    DWORD ForwarderChain;\n"
    "    DWORD Name;\n"
    "    DWORD FirstThunk;\n"
    "} IMAGE_IMPORT_DESCRIPTOR, *PIMAGE_IMPORT_DESCRIPTOR;\n"
    "\n"
    "typedef struct _IMAGE_DELAYLOAD_DESCRIPTOR {\n"
    "    union {\n"
    "        DWORD AllAttributes;\n"
    "        struct {\n"
    "            DWORD RvaBased : 1;\n"
    "            DWORD ReservedAttributes : 31;\n"
    "        } Attributes;\n"
    "    } Attributes;\n"
    "    DWORD DllNameRVA;\n"
    "    DWORD ModuleHandleRVA;\n"
    "    DWORD ImportAddressTableRVA;\n"
    "    DWORD ImportNameTableRVA;\n"
    "    DWORD BoundImportAddressTableRVA;\n"
    "    DWORD UnloadInformationTableRVA;\n"
    "    DWORD TimeDateStamp;\n"
    "} IMAGE_DELAYLOAD_DESCRIPTOR, *PIMAGE_DELAYLOAD_DESCRIPTOR;\n"
    "\n"
    "typedef struct _IMAGE_THUNK_DATA {\n"
    "    union {\n"
    "        ULONG_PTR ForwarderString;\n"
    "        ULONG_PTR Function;\n"
    "        ULONG_PTR Ordinal;\n"
    "        ULONG_PTR AddressOfData;\n"
    "    } u1;\n"
    "} IMAGE_THUNK_DATA, *PIMAGE_THUNK_DATA;\n"
    "\n"
    "typedef struct _IMAGE_IMPORT_BY_NAME {\n"
    "    WORD Hint;\n"
    "    char Name[1];\n"
    "} IMAGE_IMPORT_BY_NAME, *PIMAGE_IMPORT_BY_NAME;\n"
    "\n"
    "typedef struct _IMAGE_BASE_RELOCATION {\n"
    "    DWORD VirtualAddress;\n"
    "    DWORD SizeOfBlock;\n"
    "} IMAGE_BASE_RELOCATION, *PIMAGE_BASE_RELOCATION;\n"
    "\n"
    "typedef struct _IMAGE_TLS_DIRECTORY {\n"
    "    ULONG_PTR StartAddressOfRawData;\n"
    "    ULONG_PTR EndAddressOfRawData;\n"
    "    ULONG_PTR AddressOfIndex;\n"
    "    ULONG_PTR AddressOfCallBacks;\n"
    "    DWORD SizeOfZeroFill;\n"
    "    DWORD Characteristics;\n"
    "} IMAGE_TLS_DIRECTORY, *PIMAGE_TLS_DIRECTORY;\n"
    "\n"
    "typedef struct _RUNTIME_FUNCTION {\n"
    "    DWORD BeginAddress;\n"
    "    DWORD EndAddress;\n"
    "    DWORD UnwindData;\n"
    "} RUNTIME_FUNCTION, *PRUNTIME_FUNCTION;\n"
    "\n"
    "typedef struct _IMAGE_LOAD_CONFIG_CODE_INTEGRITY {\n"
    "    WORD    Flags;\n"
    "    WORD    Catalog;\n"
    "    DWORD   CatalogOffset;\n"
    "    DWORD   Reserved;\n"
    "} IMAGE_LOAD_CONFIG_CODE_INTEGRITY, *PIMAGE_LOAD_CONFIG_CODE_INTEGRITY;\n"
    "\n"
    "#ifdef _WIN64\n"
    "typedef struct _IMAGE_LOAD_CONFIG_DIRECTORY64 {\n"
    "    DWORD      Size;\n"
    "    DWORD      TimeDateStamp;\n"
    "    WORD       MajorVersion;\n"
    "    WORD       MinorVersion;\n"
    "    DWORD      GlobalFlagsClear;\n"
    "    DWORD      GlobalFlagsSet;\n"
    "    DWORD      CriticalSectionDefaultTimeout;\n"
    "    DWORD64    DeCommitFreeBlockThreshold;\n"
    "    DWORD64    DeCommitTotalFreeThreshold;\n"
    "    DWORD64    LockPrefixTable;                // VA\n"
    "    DWORD64    MaximumAllocationSize;\n"
    "    DWORD64    VirtualMemoryThreshold;\n"
    "    DWORD64    ProcessAffinityMask;\n"
    "    DWORD      ProcessHeapFlags;\n"
    "    WORD       CSDVersion;\n"
    "    WORD       DependentLoadFlags;\n"
    "    DWORD64    EditList;                       // VA\n"
    "    DWORD64    SecurityCookie;                 // VA\n"
    "    DWORD64    SEHandlerTable;                 // VA\n"
    "    DWORD64    SEHandlerCount;\n"
    "    DWORD64    GuardCFCheckFunctionPointer;    // VA\n"
    "    DWORD64    GuardCFDispatchFunctionPointer; // VA\n"
    "    DWORD64    GuardCFFunctionTable;           // VA\n"
    "    DWORD64    GuardCFFunctionCount;\n"
    "    DWORD      GuardFlags;\n"
    "    IMAGE_LOAD_CONFIG_CODE_INTEGRITY CodeIntegrity;\n"
    "    DWORD64    GuardAddressTakenIatEntryTable; // VA\n"
    "    DWORD64    GuardAddressTakenIatEntryCount;\n"
    "    DWORD64    GuardLongJumpTargetTable;       // VA\n"
    "    DWORD64    GuardLongJumpTargetCount;\n"
    "    DWORD64    DynamicValueRelocTable;         // VA\n"
    "    DWORD64    CHPEMetadataPointer;            // VA\n"
    "    DWORD64    GuardVerifyStackPointerFunctionPointer; // VA\n"
    "    DWORD      HotPatchTableOffset;\n"
    "    DWORD      Reserved3;\n"
    "    DWORD64    EnclaveConfigurationPointer;     // VA\n"
    "    DWORD64    VolatileMetadataPointer;         // VA\n"
    "    DWORD64    GuardEHContinuationTable;        // VA\n"
    "    DWORD64    GuardEHContinuationCount;\n"
    "    DWORD64    GuardXfgCheckFunctionPointer;    // VA\n"
    "    DWORD64    GuardXfgDispatchFunctionPointer; // VA\n"
    "    DWORD64    GuardXfgTableDispatchFunctionPointer; // VA\n"
    "    DWORD      CastGuardOsDeterminedFailureMode;\n"
    "    DWORD      GuardFlags2;\n"
    "} IMAGE_LOAD_CONFIG_DIRECTORY64, *PIMAGE_LOAD_CONFIG_DIRECTORY64;\n"
    "typedef IMAGE_LOAD_CONFIG_DIRECTORY64 IMAGE_LOAD_CONFIG_DIRECTORY;\n"
    "typedef IMAGE_LOAD_CONFIG_DIRECTORY64* PIMAGE_LOAD_CONFIG_DIRECTORY;\n"
    "#else\n"
    "typedef struct _IMAGE_LOAD_CONFIG_DIRECTORY32 {\n"
    "    DWORD   Size;\n"
    "    DWORD   TimeDateStamp;\n"
    "    WORD    MajorVersion;\n"
    "    WORD    MinorVersion;\n"
    "    DWORD   GlobalFlagsClear;\n"
    "    DWORD   GlobalFlagsSet;\n"
    "    DWORD   CriticalSectionDefaultTimeout;\n"
    "    DWORD   DeCommitFreeBlockThreshold;\n"
    "    DWORD   DeCommitTotalFreeThreshold;\n"
    "    DWORD   LockPrefixTable;                // VA\n"
    "    DWORD   MaximumAllocationSize;\n"
    "    DWORD   VirtualMemoryThreshold;\n"
    "    DWORD   ProcessAffinityMask;\n"
    "    DWORD   ProcessHeapFlags;\n"
    "    WORD    CSDVersion;\n"
    "    WORD    DependentLoadFlags;\n"
    "    DWORD   EditList;                       // VA\n"
    "    DWORD   SecurityCookie;                 // VA\n"
    "    DWORD   SEHandlerTable;                 // VA\n"
    "    DWORD   SEHandlerCount;\n"
    "    DWORD   GuardCFCheckFunctionPointer;    // VA\n"
    "    DWORD   GuardCFDispatchFunctionPointer; // VA\n"
    "    DWORD   GuardCFFunctionTable;           // VA\n"
    "    DWORD   GuardCFFunctionCount;\n"
    "    DWORD   GuardFlags;\n"
    "    IMAGE_LOAD_CONFIG_CODE_INTEGRITY CodeIntegrity;\n"
    "    DWORD   GuardAddressTakenIatEntryTable; // VA\n"
    "    DWORD   GuardAddressTakenIatEntryCount;\n"
    "    DWORD   GuardLongJumpTargetTable;       // VA\n"
    "    DWORD   GuardLongJumpTargetCount;\n"
    "    DWORD   DynamicValueRelocTable;         // VA\n"
    "    DWORD   CHPEMetadataPointer;            // VA\n"
    "    DWORD   GuardVerifyStackPointerFunctionPointer; // VA\n"
    "    DWORD   HotPatchTableOffset;\n"
    "    DWORD   Reserved3;\n"
    "    DWORD   EnclaveConfigurationPointer;     // VA\n"
    "    DWORD   VolatileMetadataPointer;         // VA\n"
    "    DWORD   GuardEHContinuationTable;        // VA\n"
    "    DWORD   GuardEHContinuationCount;\n"
    "    DWORD   GuardXfgCheckFunctionPointer;    // VA\n"
    "    DWORD   GuardXfgDispatchFunctionPointer; // VA\n"
    "    DWORD   GuardXfgTableDispatchFunctionPointer; // VA\n"
    "    DWORD   CastGuardOsDeterminedFailureMode;\n"
    "    DWORD   GuardFlags2;\n"
    "} IMAGE_LOAD_CONFIG_DIRECTORY32, *PIMAGE_LOAD_CONFIG_DIRECTORY32;\n"
    "typedef IMAGE_LOAD_CONFIG_DIRECTORY32 IMAGE_LOAD_CONFIG_DIRECTORY;\n"
    "typedef IMAGE_LOAD_CONFIG_DIRECTORY32* PIMAGE_LOAD_CONFIG_DIRECTORY;\n"
    "#endif\n"
    "\n"
    "typedef struct _API_SET_NAMESPACE {\n"
    "    ULONG Version;\n"
    "    ULONG Size;\n"
    "    ULONG Flags;\n"
    "    ULONG Count;\n"
    "    ULONG EntryOffset;\n"
    "    ULONG HashOffset;\n"
    "    ULONG HashFactor;\n"
    "} API_SET_NAMESPACE, *PAPI_SET_NAMESPACE;\n"
    "\n"
    "typedef struct _API_SET_NAMESPACE_ENTRY {\n"
    "    ULONG Flags;\n"
    "    ULONG NameOffset;\n"
    "    ULONG NameLength;\n"
    "    ULONG AliasLength;\n"
    "    ULONG ValueOffset;\n"
    "    ULONG ValueCount;\n"
    "} API_SET_NAMESPACE_ENTRY, *PAPI_SET_NAMESPACE_ENTRY;\n"
    "\n"
    "typedef struct _API_SET_VALUE_ENTRY {\n"
    "    ULONG Flags;\n"
    "    ULONG NameOffset;\n"
    "    ULONG NameLength;\n"
    "    ULONG ValueOffset;\n"
    "    ULONG ValueLength;\n"
    "} API_SET_VALUE_ENTRY, *PAPI_SET_VALUE_ENTRY;\n"
    "\n"
    "// --- Function Pointer Types ---\n"
    "\n"
    "typedef NTSTATUS (WINABI *fLdrLoadDll)(PWSTR, PULONG, PUNICODE_STRING, PVOID*);\n"
    "typedef NTSTATUS (WINABI *fLdrGetProcedureAddress)(PVOID, PANSI_STRING, ULONG, PVOID*);\n"
    "typedef VOID (WINABI *fRtlInitAnsiString)(PANSI_STRING, const char*);\n"
    "typedef NTSTATUS (WINABI *fRtlAnsiStringToUnicodeString)(PUNICODE_STRING, PANSI_STRING, BOOLEAN);\n"
    "typedef VOID (WINABI *fRtlFreeUnicodeString)(PUNICODE_STRING);\n"
    "typedef LPVOID (WINABI *fVirtualAlloc)(LPVOID, SIZE_T, DWORD, DWORD);\n"
    "typedef BOOL (WINABI *fVirtualFree)(LPVOID, SIZE_T, DWORD);\n"
    "typedef BOOL (WINABI *fVirtualProtect)(LPVOID, SIZE_T, DWORD, PDWORD);\n"
    "typedef BOOL (WINABI *fRtlAddFunctionTable)(PRUNTIME_FUNCTION, DWORD, DWORD64);\n"
    "typedef VOID (WINABI *PIMAGE_TLS_CALLBACK)(PVOID, DWORD, PVOID);\n"
    "typedef DWORD (WINABI *fTlsAlloc)(VOID);\n"
    "typedef LPVOID (WINABI *fTlsGetValue)(DWORD);\n"
    "typedef BOOL (WINABI *fTlsSetValue)(DWORD, LPVOID);\n"
    "typedef LPVOID (WINABI *fGetProcAddress)(HMODULE, const char*);\n"
    "typedef HANDLE (WINABI *fGetProcessHeap)(VOID);\n"
    "typedef LPVOID (WINABI *fHeapAlloc)(HANDLE, DWORD, SIZE_T);\n"
    "typedef BOOL (WINABI *fHeapFree)(HANDLE, DWORD, LPVOID);\n"
    "typedef HANDLE (WINABI *fCreateThread)(LPVOID, SIZE_T, LPVOID, LPVOID, DWORD, LPDWORD);\n"
    "typedef HANDLE (WINABI *fGetStdHandle)(DWORD);\n"
    "typedef BOOL (WINABI *fWriteFile)(HANDLE, LPVOID, DWORD, LPDWORD, LPVOID);\n"
    "typedef BOOL (WINABI *fReadFile)(HANDLE, LPVOID, DWORD, LPDWORD, LPVOID);\n"
    "typedef HMODULE (WINABI *fGetModuleHandleA)(const char*);\n"
    "typedef HMODULE (WINABI *fGetModuleHandleW)(const WCHAR*);\n"
    "typedef DWORD (WINABI *fGetModuleFileNameA)(HMODULE, char*, DWORD);\n"
    "typedef DWORD (WINABI *fGetModuleFileNameW)(HMODULE, WCHAR*, DWORD);\n"
    "typedef BOOL (WINABI *fGetModuleHandleExA)(DWORD, const char*, HMODULE*);\n"
    "typedef BOOL (WINABI *fGetModuleHandleExW)(DWORD, const WCHAR*, HMODULE*);\n"
    "\n"
    "#define GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS 0x00000004\n"
    "#define GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT 0x00000002\n"
    "\n"
    "#define STD_INPUT_HANDLE  ((DWORD)-10)\n"
    "#define STD_OUTPUT_HANDLE ((DWORD)-11)\n"
    "\n"
    "// --- PEB / TEB Access ---\n"
    "\n"
    "#ifdef _MSC_VER\n"
    "#include <intrin.h>\n"
    "#define GET_PEB() (PVOID)(sizeof(PVOID) == 8 ? __readgsqword(0x60) : __readfsdword(0x30))\n"
    "#define GET_TEB() (PVOID)(sizeof(PVOID) == 8 ? __readgsqword(0x30) : __readfsdword(0x18))\n"
    "#else\n"
    "static __inline__ PVOID GET_PEB() {\n"
    "    PVOID peb;\n"
    "#ifdef _WIN64\n"
    "    __asm__(\"mov %%gs:0x60, %0\" : \"=r\" (peb));\n"
    "#else\n"
    "    __asm__(\"mov %%fs:0x30, %0\" : \"=r\" (peb));\n"
    "#endif\n"
    "    return peb;\n"
    "}\n"
    "static __inline__ PVOID GET_TEB() {\n"
    "    PVOID teb;\n"
    "#ifdef _WIN64\n"
    "    __asm__(\"mov %%gs:0x30, %0\" : \"=r\" (teb));\n"
    "#else\n"
    "    __asm__(\"mov %%fs:0x18, %0\" : \"=r\" (teb));\n"
    "#endif\n"
    "    return teb;\n"
    "}\n"
    "#endif\n"
    "\n"
    "// --- Global Variables ---\n"
    "static PIMAGE_TLS_DIRECTORY g_tls_dir = NULL;\n"
    "static DWORD g_tls_index = 0xFFFFFFFF;\n"
    "static fVirtualAlloc g_vAlloc = NULL;\n"
    "static fVirtualFree g_vFree = NULL;\n"
    "static fTlsGetValue g_fTlsGetValue = NULL;\n"
    "static fTlsSetValue g_fTlsSetValue = NULL;\n"
    "static fGetProcessHeap g_fGetProcessHeap = NULL;\n"
    "static fHeapAlloc g_fHeapAlloc = NULL;\n"
    "static fHeapFree g_fHeapFree = NULL;\n"
    "static fCreateThread g_origCreateThread = NULL;\n"
    "static fGetProcAddress g_origGetProcAddress = NULL;\n"
    "static fGetModuleHandleA g_origGetModuleHandleA = NULL;\n"
    "static fGetModuleHandleW g_origGetModuleHandleW = NULL;\n"
    "static fGetModuleFileNameA g_origGetModuleFileNameA = NULL;\n"
    "static fGetModuleFileNameW g_origGetModuleFileNameW = NULL;\n"
    "static fGetModuleHandleExA g_origGetModuleHandleExA = NULL;\n"
    "static fGetModuleHandleExW g_origGetModuleHandleExW = NULL;\n"
    "static fRtlInitAnsiString g_RtlInitAnsiString = NULL;\n"
    "static fLdrGetProcedureAddress g_LdrGetProcedureAddress = NULL;\n"
    "static fLdrLoadDll g_LdrLoadDll = NULL;\n"
    "static fRtlAnsiStringToUnicodeString g_RtlAnsiStringToUnicodeString = NULL;\n"
    "static fRtlFreeUnicodeString g_RtlFreeUnicodeString = NULL;\n"
    "\n"
    "static PVOID g_pe_base = NULL;\n"
    "static BOOL g_is_dll = FALSE;\n"
    "static DWORD g_entry_point_rva = 0;\n"
    "\n"
    "// --- Helper Functions ---\n"
    "\n"
    "static void* my_memcpy(void* dest, const void* src, SIZE_T n) {\n"
    "    char* d = (char*)dest;\n"
    "    const char* s = (const char*)src;\n"
    "    if (!d || !s) return dest;\n"
    "    while (n--) *d++ = *s++;\n"
    "    return dest;\n"
    "}\n"
    "\n"
    "static void* my_memset(void* s, int c, SIZE_T n) {\n"
    "    unsigned char* p = (unsigned char*)s;\n"
    "    if (!p) return s;\n"
    "    while (n--) *p++ = (unsigned char)c;\n"
    "    return s;\n"
    "}\n"
    "\n"
    "static int my_strlen(const char* s) {\n"
    "    int l = 0;\n"
    "    while (s && s[l]) l++;\n"
    "    return l;\n"
    "}\n"
    "\n"
    "static int my_strcmp(const char* s1, const char* s2) {\n"
    "    if (!s1 || !s2) return -1;\n"
    "    while (*s1 && (*s1 == *s2)) { s1++; s2++; }\n"
    "    return *(unsigned char*)s1 - *(unsigned char*)s2;\n"
    "}\n"
    "\n"
    "static int my_strncmp(const char* s1, const char* s2, SIZE_T n) {\n"
    "    if (!s1 || !s2) return -1;\n"
    "    while (n && *s1 && (*s1 == *s2)) { s1++; s2++; n--; }\n"
    "    if (n == 0) return 0;\n"
    "    return *(unsigned char*)s1 - *(unsigned char*)s2;\n"
    "}\n"
    "\n"
    "// --- Manual Resolution Logic ---\n"
    "\n"
    "static PVOID get_module_handle_manual(const char* dll_name) {\n"
    "    PPEB peb = (PPEB)GET_PEB();\n"
    "    PLIST_ENTRY head = &peb->Ldr->InLoadOrderModuleList;\n"
    "    PLIST_ENTRY curr = head->Flink;\n"
    "    while (curr != head) {\n"
    "        PLDR_DATA_TABLE_ENTRY entry = (PLDR_DATA_TABLE_ENTRY)curr;\n"
    "        if (dll_name == NULL) return entry->DllBase;\n"
    "        WCHAR w_dll_name[MAX_PATH];\n"
    "        int i = 0;\n"
    "        while (dll_name[i] && i < MAX_PATH - 1) { w_dll_name[i] = (WCHAR)dll_name[i]; i++; }\n"
    "        w_dll_name[i] = 0;\n"
    "        int match = 1;\n"
    "        if (entry->BaseDllName.Length / 2 >= (USHORT)i) {\n"
    "            for (int j = 0; j < i; j++) {\n"
    "                WCHAR c1 = w_dll_name[j];\n"
    "                WCHAR c2 = entry->BaseDllName.Buffer[j];\n"
    "                if (c1 >= 'A' && c1 <= 'Z') c1 += 32;\n"
    "                if (c2 >= 'A' && c2 <= 'Z') c2 += 32;\n"
    "                if (c1 != c2) { match = 0; break; }\n"
    "            }\n"
    "            if (match && (entry->BaseDllName.Length / 2 == (USHORT)i || entry->BaseDllName.Buffer[i] == 0)) return entry->DllBase;\n"
    "        }\n"
    "        curr = curr->Flink;\n"
    "    }\n"
    "    return NULL;\n"
    "}\n"
    "\n"
    "#define API_SET_NAMESPACE_OFFSET (sizeof(PVOID) == 8 ? 0x68 : 0x38)\n"
    "\n"
    "static void resolve_api_set(const char* dll_name, char* out_name) {\n"
    "    if (my_strncmp(dll_name, \"api-\", 4) != 0 && my_strncmp(dll_name, \"ext-\", 4) != 0) {\n"
    "        int i = 0; while (dll_name[i]) { out_name[i] = dll_name[i]; i++; } out_name[i] = '\\0';\n"
    "        return;\n"
    "    }\n"
    "    PVOID peb = GET_PEB();\n"
    "    PAPI_SET_NAMESPACE api_set_map = *(PAPI_SET_NAMESPACE*)((char*)peb + API_SET_NAMESPACE_OFFSET);\n"
    "    if (api_set_map->Version < 6) {\n"
    "        int i = 0; while (dll_name[i]) { out_name[i] = dll_name[i]; i++; } out_name[i] = '\\0';\n"
    "        return;\n"
    "    }\n"
    "    PAPI_SET_NAMESPACE_ENTRY entries = (PAPI_SET_NAMESPACE_ENTRY)((char*)api_set_map + api_set_map->EntryOffset);\n"
    "    SIZE_T dll_name_len = my_strlen(dll_name);\n"
    "    if (dll_name_len > 4 && (dll_name[dll_name_len - 4] == '.')) dll_name_len -= 4;\n"
    "    for (ULONG i = 0; i < api_set_map->Count; i++) {\n"
    "        PAPI_SET_NAMESPACE_ENTRY entry = &entries[i];\n"
    "        PWSTR name = (PWSTR)((char*)api_set_map + entry->NameOffset);\n"
    "        if (dll_name_len == (SIZE_T)entry->NameLength / 2) {\n"
    "            int match = 1;\n"
    "            for (SIZE_T j = 0; j < dll_name_len; j++) {\n"
    "                WCHAR c1 = (WCHAR)dll_name[j]; WCHAR c2 = name[j];\n"
    "                if (c1 >= 'A' && c1 <= 'Z') c1 += 32;\n"
    "                if (c2 >= 'A' && c2 <= 'Z') c2 += 32;\n"
    "                if (c1 != c2) { match = 0; break; }\n"
    "            }\n"
    "            if (match) {\n"
    "                PAPI_SET_VALUE_ENTRY values = (PAPI_SET_VALUE_ENTRY)((char*)api_set_map + entry->ValueOffset);\n"
    "                if (entry->ValueCount > 0) {\n"
    "                    PAPI_SET_VALUE_ENTRY value = &values[0];\n"
    "                    PWSTR target_dll_wide = (PWSTR)((char*)api_set_map + value->ValueOffset);\n"
    "                    ULONG target_dll_len = value->ValueLength / 2;\n"
    "                    for (ULONG k = 0; k < target_dll_len; k++) out_name[k] = (char)target_dll_wide[k];\n"
    "                    out_name[target_dll_len] = '\\0';\n"
    "                    return;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "    int k = 0; while (dll_name[k]) { out_name[k] = dll_name[k]; k++; } out_name[k] = '\\0';\n"
    "}\n"
    "\n"
    "static PVOID get_export_address_manual_recursive(HMODULE h_module, const char* func_name, fRtlInitAnsiString _RtlInitAnsiString, fLdrGetProcedureAddress _LdrGetProcedureAddress, fLdrLoadDll _LdrLoadDll, fRtlAnsiStringToUnicodeString _RtlAnsiStringToUnicodeString, fRtlFreeUnicodeString _RtlFreeUnicodeString, int depth) {\n"
    "    if (!h_module || depth > 10) return NULL;\n"
    "\n"
    "    PIMAGE_DOS_HEADER dos_header = (PIMAGE_DOS_HEADER)h_module;\n"
    "    PIMAGE_NT_HEADERS nt_headers = (PIMAGE_NT_HEADERS)((char*)h_module + dos_header->e_lfanew);\n"
    "    IMAGE_DATA_DIRECTORY export_dir_info = nt_headers->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT];\n"
    "    if (export_dir_info.Size == 0) return NULL;\n"
    "    PIMAGE_EXPORT_DIRECTORY export_dir = (PIMAGE_EXPORT_DIRECTORY)((char*)h_module + export_dir_info.VirtualAddress);\n"
    "    PDWORD names = (PDWORD)((char*)h_module + export_dir->AddressOfNames);\n"
    "    PDWORD functions = (PDWORD)((char*)h_module + export_dir->AddressOfFunctions);\n"
    "    PWORD ordinals = (PWORD)((char*)h_module + export_dir->AddressOfNameOrdinals);\n"
    "    PVOID addr = NULL;\n"
    "    if (IMAGE_SNAP_BY_ORDINAL((ULONG_PTR)func_name)) {\n"
    "        WORD ordinal = (WORD)IMAGE_ORDINAL((ULONG_PTR)func_name) - (WORD)export_dir->Base;\n"
    "        addr = (PVOID)((char*)h_module + functions[ordinal]);\n"
    "    } else {\n"
    "        for (DWORD i = 0; i < export_dir->NumberOfNames; i++) {\n"
    "            if (my_strcmp(func_name, (char*)h_module + names[i]) == 0) {\n"
    "                addr = (PVOID)((char*)h_module + functions[ordinals[i]]);\n"
    "                break;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "    if (!addr) return NULL;\n"
    "    if ((char*)addr >= (char*)export_dir && (char*)addr < (char*)export_dir + export_dir_info.Size) {\n"
    "        char forward_str[MAX_PATH];\n"
    "        int i = 0;\n"
    "        while (((char*)addr)[i] != '\\0' && i < MAX_PATH - 1) { forward_str[i] = ((char*)addr)[i]; i++; }\n"
    "        forward_str[i] = '\\0';\n"
    "        char* dot = NULL;\n"
    "        for (int j = 0; j < i; j++) { if (forward_str[j] == '.') { dot = &forward_str[j]; break; } }\n"
    "        if (dot) {\n"
    "            *dot = '\\0';\n"
    "            char dll_name[MAX_PATH];\n"
    "            int k = 0;\n"
    "            while (forward_str[k]) { dll_name[k] = forward_str[k]; k++; }\n"
    "            int has_ext = 0;\n"
    "            for(int m=0; m<k; m++) if(dll_name[m] == '.') has_ext = 1;\n"
    "            if(!has_ext) { dll_name[k++] = '.'; dll_name[k++] = 'd'; dll_name[k++] = 'l'; dll_name[k++] = 'l'; dll_name[k] = '\\0'; }\n"
    "            else { dll_name[k] = '\\0'; }\n"
    "            char real_dll[MAX_PATH];\n"
    "            resolve_api_set(dll_name, real_dll);\n"
    "            HMODULE h_forward = get_module_handle_manual(real_dll);\n"
    "            if (!h_forward && _RtlInitAnsiString && _RtlAnsiStringToUnicodeString && _LdrLoadDll && _RtlFreeUnicodeString) {\n"
    "                ANSI_STRING a_dll; UNICODE_STRING u_dll;\n"
    "                _RtlInitAnsiString(&a_dll, real_dll);\n"
    "                _RtlAnsiStringToUnicodeString(&u_dll, &a_dll, TRUE);\n"
    "                _LdrLoadDll(NULL, NULL, &u_dll, (PVOID*)&h_forward);\n"
    "                _RtlFreeUnicodeString(&u_dll);\n"
    "            }\n"
    "            if (h_forward) {\n"
    "                return get_export_address_manual_recursive(h_forward, dot + 1, _RtlInitAnsiString, _LdrGetProcedureAddress, _LdrLoadDll, _RtlAnsiStringToUnicodeString, _RtlFreeUnicodeString, depth + 1);\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "    return addr;\n"
    "}\n"
    "\n"
    "static PVOID get_export_address_manual(HMODULE h_module, const char* func_name, fRtlInitAnsiString _RtlInitAnsiString, fLdrGetProcedureAddress _LdrGetProcedureAddress, fLdrLoadDll _LdrLoadDll, fRtlAnsiStringToUnicodeString _RtlAnsiStringToUnicodeString, fRtlFreeUnicodeString _RtlFreeUnicodeString) {\n"
    "    return get_export_address_manual_recursive(h_module, func_name, _RtlInitAnsiString, _LdrGetProcedureAddress, _LdrLoadDll, _RtlAnsiStringToUnicodeString, _RtlFreeUnicodeString, 0);\n"
    "}\n"
    "\n"
    "// --- TLS Initialization Helper ---\n"
    "\n"
    "static VOID init_thread_tls() {\n"
    "    if (!g_tls_dir || !g_fTlsSetValue || !g_fTlsGetValue || !g_vAlloc || g_tls_index == 0xFFFFFFFF) return;\n"
    "\n"
    "    if (g_fTlsGetValue(g_tls_index) != NULL) return;\n"
    "\n"
    "    SIZE_T tls_data_size = (SIZE_T)(g_tls_dir->EndAddressOfRawData - g_tls_dir->StartAddressOfRawData);\n"
    "    SIZE_T total_tls_size = tls_data_size + g_tls_dir->SizeOfZeroFill;\n"
    "    if (total_tls_size == 0) total_tls_size = 8;\n"
    "\n"
    "    // Use VirtualAlloc for TLS data to ensure 4KB alignment (critical for some SIMD/Rust structures)\n"
    "    LPVOID thread_tls_data = g_vAlloc(NULL, total_tls_size, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);\n"
    "    if (thread_tls_data) {\n"
    "        if (tls_data_size > 0 && g_tls_dir->StartAddressOfRawData) {\n"
    "            my_memcpy(thread_tls_data, (const void*)g_tls_dir->StartAddressOfRawData, tls_data_size);\n"
    "        }\n"
    "        if (g_tls_dir->SizeOfZeroFill > 0) {\n"
    "            my_memset((char*)thread_tls_data + tls_data_size, 0, g_tls_dir->SizeOfZeroFill);\n"
    "        }\n"
    "\n"
    "        g_fTlsSetValue(g_tls_index, thread_tls_data);\n"
    "\n"
    "        // Update the static TLS pointer array in the TEB (ThreadLocalStoragePointer)\n"
    "        // This is where __declspec(thread) variables are looked up via the TLS index.\n"
    "        void*** tls_pointer_array_ptr = (void***)((char*)GET_TEB() + (sizeof(PVOID) == 8 ? 0x58 : 0x2C));\n"
    "        if (*tls_pointer_array_ptr && g_tls_index < 64) {\n"
    "            // 64 is a conservative limit for the pre-allocated array in most Windows processes.\n"
    "            (*tls_pointer_array_ptr)[g_tls_index] = thread_tls_data;\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "static VOID init_security_cookie() {\n"
    "    PIMAGE_NT_HEADERS nt = (PIMAGE_NT_HEADERS)((char*)g_pe_base + ((PIMAGE_DOS_HEADER)g_pe_base)->e_lfanew);\n"
    "    IMAGE_DATA_DIRECTORY load_config_dir = nt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG];\n"
    "    if (load_config_dir.Size > 0) {\n"
    "        PIMAGE_LOAD_CONFIG_DIRECTORY load_config = (PIMAGE_LOAD_CONFIG_DIRECTORY)((char*)g_pe_base + load_config_dir.VirtualAddress);\n"
    "        if (load_config->SecurityCookie) {\n"
    "            ULONG_PTR cookie = (ULONG_PTR)load_config->SecurityCookie;\n"
    "            // Only initialize if the cookie is the default one (0xBB40E64E or 0x00002B992DDFA232)\n"
    "#ifdef _WIN64\n"
    "            if (*(ULONG_PTR*)cookie == 0x00002B992DDFA232 || *(ULONG_PTR*)cookie == 0) {\n"
    "                *(ULONG_PTR*)cookie = (ULONG_PTR)GET_TEB() ^ (ULONG_PTR)g_pe_base;\n"
    "            }\n"
    "#else\n"
    "            if (*(DWORD*)cookie == 0xBB40E64E || *(DWORD*)cookie == 0) {\n"
    "                *(DWORD*)cookie = (DWORD)GET_TEB() ^ (DWORD)g_pe_base;\n"
    "            }\n"
    "#endif\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "static VOID run_tls_callbacks(DWORD reason) {\n"
    "    if (!g_tls_dir) return;\n"
    "    PIMAGE_TLS_CALLBACK* callbacks = (PIMAGE_TLS_CALLBACK*)g_tls_dir->AddressOfCallBacks;\n"
    "    if (callbacks) {\n"
    "        while (*callbacks) {\n"
    "#ifdef _WIN64\n"
    "            call_aligned((PVOID)*callbacks, (PVOID)g_pe_base, (PVOID)(ULONG_PTR)reason, NULL, NULL);\n"
    "#else\n"
    "            (*callbacks)(g_pe_base, reason, NULL);\n"
    "#endif\n"
    "            callbacks++;\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "// --- Thread Wrapper & Hook ---\n"
    "\n"
    "typedef struct _WRAPPER_ARGS {\n"
    "    LPVOID func;\n"
    "    LPVOID param;\n"
    "} WRAPPER_ARGS, *PWRAPPER_ARGS;\n"
    "\n"
    "static DWORD WINABI ThreadWrapper(LPVOID lpParam) {\n"
    "    if (!lpParam) return 0;\n"
    "    PWRAPPER_ARGS args = (PWRAPPER_ARGS)lpParam;\n"
    "    LPVOID func = args->func;\n"
    "    LPVOID param = args->param;\n"
    "\n"
    "    init_thread_tls();\n"
    "    run_tls_callbacks(DLL_THREAD_ATTACH);\n"
    "\n"
    "    if (g_is_dll) {\n"
    "        typedef BOOL (WINABI *fDllMain)(HINSTANCE, DWORD, LPVOID);\n"
    "        PIMAGE_NT_HEADERS nt = (PIMAGE_NT_HEADERS)((char*)g_pe_base + ((PIMAGE_DOS_HEADER)g_pe_base)->e_lfanew);\n"
    "        fDllMain dll_main = (fDllMain)((char*)g_pe_base + nt->OptionalHeader.AddressOfEntryPoint);\n"
    "#ifdef _WIN64\n"
    "        call_aligned((PVOID)dll_main, (PVOID)g_pe_base, (PVOID)DLL_THREAD_ATTACH, NULL, NULL);\n"
    "#else\n"
    "        dll_main((HINSTANCE)g_pe_base, DLL_THREAD_ATTACH, NULL);\n"
    "#endif\n"
    "    }\n"
    "\n"
    "    DWORD result;\n"
    "#ifdef _WIN64\n"
    "    result = (DWORD)call_aligned((PVOID)func, (PVOID)param, NULL, NULL, NULL);\n"
    "#else\n"
    "    result = ((DWORD(WINABI*)(LPVOID))func)(param);\n"
    "#endif\n"
    "\n"
    "    if (g_is_dll) {\n"
    "        typedef BOOL (WINABI *fDllMain)(HINSTANCE, DWORD, LPVOID);\n"
    "        PIMAGE_NT_HEADERS nt = (PIMAGE_NT_HEADERS)((char*)g_pe_base + ((PIMAGE_DOS_HEADER)g_pe_base)->e_lfanew);\n"
    "        fDllMain dll_main = (fDllMain)((char*)g_pe_base + nt->OptionalHeader.AddressOfEntryPoint);\n"
    "#ifdef _WIN64\n"
    "        call_aligned((PVOID)dll_main, (PVOID)g_pe_base, (PVOID)DLL_THREAD_DETACH, NULL, NULL);\n"
    "#else\n"
    "        dll_main((HINSTANCE)g_pe_base, DLL_THREAD_DETACH, NULL);\n"
    "#endif\n"
    "    }\n"
    "\n"
    "    run_tls_callbacks(DLL_THREAD_DETACH);\n"
    "\n"
    "    // DONT free TLS data here. It causes \"global allocator may not use TLS with destructors\" in Rust.\n"
    "    // System thread cleanup will eventually reclaim what it can, and modern allocators handle this better if we don't yank memory early.\n"
    "\n"
    "    if (g_fHeapFree && g_fGetProcessHeap) g_fHeapFree(g_fGetProcessHeap(), 0, args);\n"
    "    return result;\n"
    "}\n"
    "\n"
    "static HANDLE WINABI HookedCreateThread(LPVOID lpThreadAttributes, SIZE_T dwStackSize, LPVOID lpStartAddress, LPVOID lpParameter, DWORD dwCreationFlags, LPDWORD lpThreadId) {\n"
    "    if (!g_origCreateThread || !g_fHeapAlloc || !g_fGetProcessHeap) return NULL;\n"
    "    PWRAPPER_ARGS args = (PWRAPPER_ARGS)g_fHeapAlloc(g_fGetProcessHeap(), 0, sizeof(WRAPPER_ARGS));\n"
    "    if (!args) return NULL;\n"
    "    args->func = lpStartAddress;\n"
    "    args->param = lpParameter;\n"
    "    HANDLE hThread = g_origCreateThread(lpThreadAttributes, dwStackSize, (LPVOID)ThreadWrapper, args, dwCreationFlags, lpThreadId);\n"
    "    if (!hThread && g_fHeapFree) {\n"
    "        g_fHeapFree(g_fGetProcessHeap(), 0, args);\n"
    "    }\n"
    "    return hThread;\n"
    "}\n"
    "\n"
    "static LPVOID WINABI HookedTlsGetValue(DWORD dwTlsIndex) {\n"
    "    if (dwTlsIndex == g_tls_index) {\n"
    "        LPVOID val = g_fTlsGetValue(dwTlsIndex);\n"
    "        if (val == NULL) {\n"
    "            init_thread_tls();\n"
    "            val = g_fTlsGetValue(dwTlsIndex);\n"
    "        }\n"
    "        return val;\n"
    "    }\n"
    "    return g_fTlsGetValue(dwTlsIndex);\n"
    "}\n"
    "\n"
    "static HMODULE WINABI HookedGetModuleHandleA(const char* lpModuleName) {\n"
    "    if (lpModuleName == NULL) return (HMODULE)g_pe_base;\n"
    "    return g_origGetModuleHandleA(lpModuleName);\n"
    "}\n"
    "\n"
    "static HMODULE WINABI HookedGetModuleHandleW(const WCHAR* lpModuleName) {\n"
    "    if (lpModuleName == NULL) return (HMODULE)g_pe_base;\n"
    "    return g_origGetModuleHandleW(lpModuleName);\n"
    "}\n"
    "\n"
    "static DWORD WINABI HookedGetModuleFileNameA(HMODULE hModule, char* lpFilename, DWORD nSize) {\n"
    "    if (hModule == NULL || hModule == (HMODULE)g_pe_base) {\n"
    "        return g_origGetModuleFileNameA(NULL, lpFilename, nSize);\n"
    "    }\n"
    "    return g_origGetModuleFileNameA(hModule, lpFilename, nSize);\n"
    "}\n"
    "\n"
    "static BOOL WINABI HookedGetModuleHandleExA(DWORD dwFlags, const char* lpModuleName, HMODULE* phModule) {\n"
    "    if (dwFlags & GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS) {\n"
    "        ULONG_PTR addr = (ULONG_PTR)lpModuleName;\n"
    "        PIMAGE_NT_HEADERS nt = (PIMAGE_NT_HEADERS)((char*)g_pe_base + ((PIMAGE_DOS_HEADER)g_pe_base)->e_lfanew);\n"
    "        if (addr >= (ULONG_PTR)g_pe_base && addr < (ULONG_PTR)g_pe_base + nt->OptionalHeader.SizeOfImage) {\n"
    "            *phModule = (HMODULE)g_pe_base;\n"
    "            return TRUE;\n"
    "        }\n"
    "    } else if (lpModuleName == NULL) {\n"
    "        *phModule = (HMODULE)g_pe_base;\n"
    "        return TRUE;\n"
    "    }\n"
    "    return g_origGetModuleHandleExA(dwFlags, lpModuleName, phModule);\n"
    "}\n"
    "\n"
    "static DWORD WINABI HookedGetModuleFileNameW(HMODULE hModule, WCHAR* lpFilename, DWORD nSize) {\n"
    "    if (hModule == NULL || hModule == (HMODULE)g_pe_base) {\n"
    "        return g_origGetModuleFileNameW(NULL, lpFilename, nSize);\n"
    "    }\n"
    "    return g_origGetModuleFileNameW(hModule, lpFilename, nSize);\n"
    "}\n"
    "\n"
    "static BOOL WINABI HookedGetModuleHandleExW(DWORD dwFlags, const WCHAR* lpModuleName, HMODULE* phModule) {\n"
    "    if (dwFlags & GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS) {\n"
    "        ULONG_PTR addr = (ULONG_PTR)lpModuleName;\n"
    "        PIMAGE_NT_HEADERS nt = (PIMAGE_NT_HEADERS)((char*)g_pe_base + ((PIMAGE_DOS_HEADER)g_pe_base)->e_lfanew);\n"
    "        if (addr >= (ULONG_PTR)g_pe_base && addr < (ULONG_PTR)g_pe_base + nt->OptionalHeader.SizeOfImage) {\n"
    "            *phModule = (HMODULE)g_pe_base;\n"
    "            return TRUE;\n"
    "        }\n"
    "    } else if (lpModuleName == NULL) {\n"
    "        *phModule = (HMODULE)g_pe_base;\n"
    "        return TRUE;\n"
    "    }\n"
    "    return g_origGetModuleHandleExW(dwFlags, lpModuleName, phModule);\n"
    "}\n"
    "\n"
    "static LPVOID WINABI HookedGetProcAddress(HMODULE hModule, const char* lpProcName) {\n"
    "    if (hModule == (HMODULE)g_pe_base) {\n"
    "        return get_export_address_manual((HMODULE)g_pe_base, lpProcName, g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "    }\n"
    "    if (lpProcName && !IMAGE_SNAP_BY_ORDINAL((ULONG_PTR)lpProcName)) {\n"
    "        if (my_strcmp(lpProcName, \"CreateThread\") == 0) return (LPVOID)HookedCreateThread;\n"
    "        if (my_strcmp(lpProcName, \"GetProcAddress\") == 0) return (LPVOID)HookedGetProcAddress;\n"
    "        if (my_strcmp(lpProcName, \"TlsGetValue\") == 0) return (LPVOID)HookedTlsGetValue;\n"
    "        if (my_strcmp(lpProcName, \"GetModuleHandleExA\") == 0) return (LPVOID)HookedGetModuleHandleExA;\n"
    "        if (my_strcmp(lpProcName, \"GetModuleHandleExW\") == 0) return (LPVOID)HookedGetModuleHandleExW;\n"
    "    }\n"
    "    return g_origGetProcAddress(hModule, lpProcName);\n"
    "}\n"
    "\n"
    "// --- Main loading logic ---\n"
    "\n"
    "// PE_BLOB_ARRAY\n"
    "unsigned char pe_blob[] = { 0 };\n"
    "// IMAGE_BASE\n"
    "ULONG_PTR image_base = 0;\n"
    "// SIZE_OF_IMAGE\n"
    "SIZE_T size_of_image = 0;\n"
    "\n"
    "void load_pe() {\n"
    "    HMODULE h_ntdll = get_module_handle_manual(\"ntdll.dll\");\n"
    "    g_RtlInitAnsiString = (fRtlInitAnsiString)get_export_address_manual(h_ntdll, \"RtlInitAnsiString\", NULL, NULL, NULL, NULL, NULL);\n"
    "    g_LdrGetProcedureAddress = (fLdrGetProcedureAddress)get_export_address_manual(h_ntdll, \"LdrGetProcedureAddress\", g_RtlInitAnsiString, NULL, NULL, NULL, NULL);\n"
    "    g_LdrLoadDll = (fLdrLoadDll)get_export_address_manual(h_ntdll, \"LdrLoadDll\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, NULL, NULL, NULL);\n"
    "    g_RtlAnsiStringToUnicodeString = (fRtlAnsiStringToUnicodeString)get_export_address_manual(h_ntdll, \"RtlAnsiStringToUnicodeString\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, NULL, NULL);\n"
    "    g_RtlFreeUnicodeString = (fRtlFreeUnicodeString)get_export_address_manual(h_ntdll, \"RtlFreeUnicodeString\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, NULL);\n"
    "\n"
    "    HMODULE h_kernel32 = get_module_handle_manual(\"kernel32.dll\");\n"
    "    g_vAlloc = (fVirtualAlloc)get_export_address_manual(h_kernel32, \"VirtualAlloc\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "    g_vFree = (fVirtualFree)get_export_address_manual(h_kernel32, \"VirtualFree\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "    fVirtualProtect _VirtualProtect = (fVirtualProtect)get_export_address_manual(h_kernel32, \"VirtualProtect\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "    fTlsAlloc _TlsAlloc = (fTlsAlloc)get_export_address_manual(h_kernel32, \"TlsAlloc\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "    g_fTlsGetValue = (fTlsGetValue)get_export_address_manual(h_kernel32, \"TlsGetValue\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "    g_fTlsSetValue = (fTlsSetValue)get_export_address_manual(h_kernel32, \"TlsSetValue\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "    g_fGetProcessHeap = (fGetProcessHeap)get_export_address_manual(h_kernel32, \"GetProcessHeap\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "    g_fHeapAlloc = (fHeapAlloc)get_export_address_manual(h_kernel32, \"HeapAlloc\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "    g_fHeapFree = (fHeapFree)get_export_address_manual(h_kernel32, \"HeapFree\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "    g_origGetProcAddress = (fGetProcAddress)get_export_address_manual(h_kernel32, \"GetProcAddress\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "    g_origGetModuleHandleA = (fGetModuleHandleA)get_export_address_manual(h_kernel32, \"GetModuleHandleA\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "    g_origGetModuleHandleW = (fGetModuleHandleW)get_export_address_manual(h_kernel32, \"GetModuleHandleW\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "    g_origGetModuleFileNameA = (fGetModuleFileNameA)get_export_address_manual(h_kernel32, \"GetModuleFileNameA\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "    g_origGetModuleFileNameW = (fGetModuleFileNameW)get_export_address_manual(h_kernel32, \"GetModuleFileNameW\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "    g_origGetModuleHandleExA = (fGetModuleHandleExA)get_export_address_manual(h_kernel32, \"GetModuleHandleExA\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "    g_origGetModuleHandleExW = (fGetModuleHandleExW)get_export_address_manual(h_kernel32, \"GetModuleHandleExW\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "\n"
    "    PIMAGE_DOS_HEADER dos_header_raw = (PIMAGE_DOS_HEADER)pe_blob;\n"
    "    PIMAGE_NT_HEADERS nt_headers_raw = (PIMAGE_NT_HEADERS)((char*)pe_blob + dos_header_raw->e_lfanew);\n"
    "    LPVOID pe_buffer = g_vAlloc(NULL, nt_headers_raw->OptionalHeader.SizeOfImage, MEM_RESERVE | MEM_COMMIT, PAGE_EXECUTE_READWRITE);\n"
    "    if (!pe_buffer) return;\n"
    "    g_pe_base = pe_buffer;\n"
    "    g_is_dll = (nt_headers_raw->FileHeader.Characteristics & IMAGE_FILE_DLL) != 0;\n"
    "    g_entry_point_rva = nt_headers_raw->OptionalHeader.AddressOfEntryPoint;\n"
    "    my_memcpy(pe_buffer, pe_blob, nt_headers_raw->OptionalHeader.SizeOfHeaders);\n"
    "    PIMAGE_SECTION_HEADER sections_raw = IMAGE_FIRST_SECTION(nt_headers_raw);\n"
    "    for (int i = 0; i < nt_headers_raw->FileHeader.NumberOfSections; i++) {\n"
    "        if (sections_raw[i].PointerToRawData != 0) {\n"
    "            my_memcpy((char*)pe_buffer + sections_raw[i].VirtualAddress, (char*)pe_blob + sections_raw[i].PointerToRawData, sections_raw[i].SizeOfRawData);\n"
    "        }\n"
    "    }\n"
    "    PIMAGE_NT_HEADERS nt_headers = (PIMAGE_NT_HEADERS)((char*)pe_buffer + ((PIMAGE_DOS_HEADER)pe_buffer)->e_lfanew);\n"
    "\n"
    "    ULONG_PTR delta = (ULONG_PTR)pe_buffer - nt_headers->OptionalHeader.ImageBase;\n"
    "    if (delta != 0) {\n"
    "        IMAGE_DATA_DIRECTORY reloc_dir = nt_headers->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_BASERELOC];\n"
    "        if (reloc_dir.Size > 0) {\n"
    "            PIMAGE_BASE_RELOCATION reloc = (PIMAGE_BASE_RELOCATION)((char*)pe_buffer + reloc_dir.VirtualAddress);\n"
    "            while (reloc->VirtualAddress != 0) {\n"
    "                DWORD count = (reloc->SizeOfBlock - sizeof(IMAGE_BASE_RELOCATION)) / sizeof(WORD);\n"
    "                WORD* list = (WORD*)((char*)reloc + sizeof(IMAGE_BASE_RELOCATION));\n"
    "                for (DWORD i = 0; i < count; i++) {\n"
    "                    WORD type = list[i] >> 12; WORD offset = list[i] & 0xFFF;\n"
    "                    if (type == IMAGE_REL_BASED_DIR64) *(ULONG_PTR*)((char*)pe_buffer + reloc->VirtualAddress + offset) += delta;\n"
    "                    else if (type == IMAGE_REL_BASED_HIGHLOW) *(DWORD*)((char*)pe_buffer + reloc->VirtualAddress + offset) += (DWORD)delta;\n"
    "                }\n"
    "                reloc = (PIMAGE_BASE_RELOCATION)((char*)reloc + reloc->SizeOfBlock);\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    IMAGE_DATA_DIRECTORY tls_dir_info = nt_headers->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_TLS];\n"
    "    if (tls_dir_info.Size > 0) {\n"
    "        g_tls_dir = (PIMAGE_TLS_DIRECTORY)((char*)pe_buffer + tls_dir_info.VirtualAddress);\n"
    "        g_tls_index = _TlsAlloc();\n"
    "        if (g_tls_index != 0xFFFFFFFF) {\n"
    "            if (g_tls_dir->AddressOfIndex) *(DWORD*)(g_tls_dir->AddressOfIndex) = g_tls_index;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    IMAGE_DATA_DIRECTORY import_dir = nt_headers->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_IMPORT];\n"
    "    if (import_dir.Size > 0) {\n"
    "        PIMAGE_IMPORT_DESCRIPTOR import_desc = (PIMAGE_IMPORT_DESCRIPTOR)((char*)pe_buffer + import_dir.VirtualAddress);\n"
    "        while (import_desc->Name) {\n"
    "            const char* dll_name = (char*)pe_buffer + import_desc->Name;\n"
    "            char resolved_dll[MAX_PATH]; resolve_api_set(dll_name, resolved_dll);\n"
    "            ANSI_STRING ansi_dll; UNICODE_STRING uni_dll;\n"
    "            g_RtlInitAnsiString(&ansi_dll, resolved_dll);\n"
    "            g_RtlAnsiStringToUnicodeString(&uni_dll, &ansi_dll, TRUE);\n"
    "            HANDLE h_module = NULL; g_LdrLoadDll(NULL, NULL, &uni_dll, &h_module); g_RtlFreeUnicodeString(&uni_dll);\n"
    "            if (h_module) {\n"
    "                PIMAGE_THUNK_DATA first_thunk = (PIMAGE_THUNK_DATA)((char*)pe_buffer + import_desc->FirstThunk);\n"
    "                PIMAGE_THUNK_DATA original_first_thunk = (PIMAGE_THUNK_DATA)((char*)pe_buffer + import_desc->OriginalFirstThunk);\n"
    "                if (!import_desc->OriginalFirstThunk) original_first_thunk = first_thunk;\n"
    "                while (original_first_thunk->u1.AddressOfData) {\n"
    "                    PVOID addr = NULL;\n"
    "                    if (IMAGE_SNAP_BY_ORDINAL(original_first_thunk->u1.Ordinal)) {\n"
    "                        addr = get_export_address_manual((HMODULE)h_module, (char*)original_first_thunk->u1.Ordinal, g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                    } else {\n"
    "                        PIMAGE_IMPORT_BY_NAME import_by_name = (PIMAGE_IMPORT_BY_NAME)((char*)pe_buffer + original_first_thunk->u1.AddressOfData);\n"
    "                        if (my_strcmp(import_by_name->Name, \"CreateThread\") == 0) {\n"
    "                            if (!g_origCreateThread) g_origCreateThread = (fCreateThread)get_export_address_manual((HMODULE)h_module, \"CreateThread\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                            addr = (PVOID)HookedCreateThread;\n"
    "                        } else if (my_strcmp(import_by_name->Name, \"GetProcAddress\") == 0) {\n"
    "                            if (!g_origGetProcAddress) g_origGetProcAddress = (fGetProcAddress)get_export_address_manual((HMODULE)h_module, \"GetProcAddress\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                            addr = (PVOID)HookedGetProcAddress;\n"
    "                        } else if (my_strcmp(import_by_name->Name, \"GetModuleHandleA\") == 0) {\n"
    "                            if (!g_origGetModuleHandleA) g_origGetModuleHandleA = (fGetModuleHandleA)get_export_address_manual((HMODULE)h_module, \"GetModuleHandleA\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                            addr = (PVOID)HookedGetModuleHandleA;\n"
    "                        } else if (my_strcmp(import_by_name->Name, \"GetModuleHandleW\") == 0) {\n"
    "                            if (!g_origGetModuleHandleW) g_origGetModuleHandleW = (fGetModuleHandleW)get_export_address_manual((HMODULE)h_module, \"GetModuleHandleW\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                            addr = (PVOID)HookedGetModuleHandleW;\n"
    "                        } else if (my_strcmp(import_by_name->Name, \"TlsGetValue\") == 0) {\n"
    "                            addr = (PVOID)HookedTlsGetValue;\n"
    "                        } else if (my_strcmp(import_by_name->Name, \"GetModuleFileNameA\") == 0) {\n"
    "                            if (!g_origGetModuleFileNameA) g_origGetModuleFileNameA = (fGetModuleFileNameA)get_export_address_manual((HMODULE)h_module, \"GetModuleFileNameA\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                            addr = (PVOID)HookedGetModuleFileNameA;\n"
    "                        } else if (my_strcmp(import_by_name->Name, \"GetModuleFileNameW\") == 0) {\n"
    "                            if (!g_origGetModuleFileNameW) g_origGetModuleFileNameW = (fGetModuleFileNameW)get_export_address_manual((HMODULE)h_module, \"GetModuleFileNameW\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                            addr = (PVOID)HookedGetModuleFileNameW;\n"
    "                        } else if (my_strcmp(import_by_name->Name, \"GetModuleHandleExA\") == 0) {\n"
    "                            if (!g_origGetModuleHandleExA) g_origGetModuleHandleExA = (fGetModuleHandleExA)get_export_address_manual((HMODULE)h_module, \"GetModuleHandleExA\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                            addr = (PVOID)HookedGetModuleHandleExA;\n"
    "                        } else if (my_strcmp(import_by_name->Name, \"GetModuleHandleExW\") == 0) {\n"
    "                            if (!g_origGetModuleHandleExW) g_origGetModuleHandleExW = (fGetModuleHandleExW)get_export_address_manual((HMODULE)h_module, \"GetModuleHandleExW\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                            addr = (PVOID)HookedGetModuleHandleExW;\n"
    "                        } else {\n"
    "                            addr = get_export_address_manual((HMODULE)h_module, (char*)import_by_name->Name, g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                        }\n"
    "                    }\n"
    "                    first_thunk->u1.Function = (ULONG_PTR)addr; first_thunk++; original_first_thunk++;\n"
    "                }\n"
    "            }\n"
    "            import_desc++;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    IMAGE_DATA_DIRECTORY delay_import_dir = nt_headers->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT];\n"
    "    if (delay_import_dir.Size > 0) {\n"
    "        PIMAGE_DELAYLOAD_DESCRIPTOR delay_desc = (PIMAGE_DELAYLOAD_DESCRIPTOR)((char*)pe_buffer + delay_import_dir.VirtualAddress);\n"
    "        while (delay_desc->DllNameRVA) {\n"
    "            const char* dll_name = (char*)pe_buffer + delay_desc->DllNameRVA;\n"
    "            char resolved_dll[MAX_PATH]; resolve_api_set(dll_name, resolved_dll);\n"
    "            ANSI_STRING ansi_dll; UNICODE_STRING uni_dll;\n"
    "            g_RtlInitAnsiString(&ansi_dll, resolved_dll);\n"
    "            g_RtlAnsiStringToUnicodeString(&uni_dll, &ansi_dll, TRUE);\n"
    "            HANDLE h_module = NULL; g_LdrLoadDll(NULL, NULL, &uni_dll, &h_module); g_RtlFreeUnicodeString(&uni_dll);\n"
    "            if (h_module) {\n"
    "                PIMAGE_THUNK_DATA first_thunk = (PIMAGE_THUNK_DATA)((char*)pe_buffer + delay_desc->ImportAddressTableRVA);\n"
    "                PIMAGE_THUNK_DATA original_first_thunk = (PIMAGE_THUNK_DATA)((char*)pe_buffer + delay_desc->ImportNameTableRVA);\n"
    "                while (original_first_thunk->u1.AddressOfData) {\n"
    "                    PVOID addr = NULL;\n"
    "                    if (IMAGE_SNAP_BY_ORDINAL(original_first_thunk->u1.Ordinal)) {\n"
    "                        addr = get_export_address_manual((HMODULE)h_module, (char*)original_first_thunk->u1.Ordinal, g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                    } else {\n"
    "                        PIMAGE_IMPORT_BY_NAME import_by_name = (PIMAGE_IMPORT_BY_NAME)((char*)pe_buffer + original_first_thunk->u1.AddressOfData);\n"
    "                        if (my_strcmp(import_by_name->Name, \"CreateThread\") == 0) {\n"
    "                            if (!g_origCreateThread) g_origCreateThread = (fCreateThread)get_export_address_manual((HMODULE)h_module, \"CreateThread\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                            addr = (PVOID)HookedCreateThread;\n"
    "                        } else if (my_strcmp(import_by_name->Name, \"GetProcAddress\") == 0) {\n"
    "                            if (!g_origGetProcAddress) g_origGetProcAddress = (fGetProcAddress)get_export_address_manual((HMODULE)h_module, \"GetProcAddress\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                            addr = (PVOID)HookedGetProcAddress;\n"
    "                        } else if (my_strcmp(import_by_name->Name, \"GetModuleHandleA\") == 0) {\n"
    "                            if (!g_origGetModuleHandleA) g_origGetModuleHandleA = (fGetModuleHandleA)get_export_address_manual((HMODULE)h_module, \"GetModuleHandleA\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                            addr = (PVOID)HookedGetModuleHandleA;\n"
    "                        } else if (my_strcmp(import_by_name->Name, \"GetModuleHandleW\") == 0) {\n"
    "                            if (!g_origGetModuleHandleW) g_origGetModuleHandleW = (fGetModuleHandleW)get_export_address_manual((HMODULE)h_module, \"GetModuleHandleW\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                            addr = (PVOID)HookedGetModuleHandleW;\n"
    "                        } else if (my_strcmp(import_by_name->Name, \"TlsGetValue\") == 0) {\n"
    "                            addr = (PVOID)HookedTlsGetValue;\n"
    "                        } else if (my_strcmp(import_by_name->Name, \"GetModuleFileNameA\") == 0) {\n"
    "                            if (!g_origGetModuleFileNameA) g_origGetModuleFileNameA = (fGetModuleFileNameA)get_export_address_manual((HMODULE)h_module, \"GetModuleFileNameA\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                            addr = (PVOID)HookedGetModuleFileNameA;\n"
    "                        } else if (my_strcmp(import_by_name->Name, \"GetModuleFileNameW\") == 0) {\n"
    "                            if (!g_origGetModuleFileNameW) g_origGetModuleFileNameW = (fGetModuleFileNameW)get_export_address_manual((HMODULE)h_module, \"GetModuleFileNameW\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                            addr = (PVOID)HookedGetModuleFileNameW;\n"
    "                        } else if (my_strcmp(import_by_name->Name, \"GetModuleHandleExA\") == 0) {\n"
    "                            if (!g_origGetModuleHandleExA) g_origGetModuleHandleExA = (fGetModuleHandleExA)get_export_address_manual((HMODULE)h_module, \"GetModuleHandleExA\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                            addr = (PVOID)HookedGetModuleHandleExA;\n"
    "                        } else if (my_strcmp(import_by_name->Name, \"GetModuleHandleExW\") == 0) {\n"
    "                            if (!g_origGetModuleHandleExW) g_origGetModuleHandleExW = (fGetModuleHandleExW)get_export_address_manual((HMODULE)h_module, \"GetModuleHandleExW\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                            addr = (PVOID)HookedGetModuleHandleExW;\n"
    "                        } else {\n"
    "                            addr = get_export_address_manual((HMODULE)h_module, (char*)import_by_name->Name, g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "                        }\n"
    "                    }\n"
    "                    first_thunk->u1.Function = (ULONG_PTR)addr; first_thunk++; original_first_thunk++;\n"
    "                }\n"
    "            }\n"
    "            delay_desc++;\n"
    "        }\n"
    "    }\n"
    "\n"
    "#ifdef _WIN64\n"
    "    IMAGE_DATA_DIRECTORY exception_dir = nt_headers->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXCEPTION];\n"
    "    if (exception_dir.Size > 0) {\n"
    "        fRtlAddFunctionTable _RtlAddFunctionTable = (fRtlAddFunctionTable)get_export_address_manual(h_ntdll, \"RtlAddFunctionTable\", g_RtlInitAnsiString, g_LdrGetProcedureAddress, g_LdrLoadDll, g_RtlAnsiStringToUnicodeString, g_RtlFreeUnicodeString);\n"
    "        if (_RtlAddFunctionTable) _RtlAddFunctionTable((PRUNTIME_FUNCTION)((char*)pe_buffer + exception_dir.VirtualAddress), exception_dir.Size / sizeof(RUNTIME_FUNCTION), (ULONG_PTR)pe_buffer);\n"
    "    }\n"
    "#endif\n"
    "\n"
    "    init_security_cookie();\n"
    "    init_thread_tls();\n"
    "    run_tls_callbacks(DLL_PROCESS_ATTACH);\n"
    "\n"
    "    PIMAGE_SECTION_HEADER sections = IMAGE_FIRST_SECTION(nt_headers);\n"
    "    for (int i = 0; i < nt_headers->FileHeader.NumberOfSections; i++) {\n"
    "        DWORD protection = 0;\n"
    "        if (sections[i].Characteristics & IMAGE_SCN_MEM_EXECUTE) {\n"
    "            if (sections[i].Characteristics & IMAGE_SCN_MEM_WRITE) protection = PAGE_EXECUTE_READWRITE;\n"
    "            else if (sections[i].Characteristics & IMAGE_SCN_MEM_READ) protection = PAGE_EXECUTE_READ;\n"
    "            else protection = PAGE_EXECUTE;\n"
    "        } else {\n"
    "            if (sections[i].Characteristics & IMAGE_SCN_MEM_WRITE) protection = PAGE_READWRITE;\n"
    "            else if (sections[i].Characteristics & IMAGE_SCN_MEM_READ) protection = PAGE_READONLY;\n"
    "            else protection = PAGE_NOACCESS;\n"
    "        }\n"
    "        DWORD old; _VirtualProtect((char*)pe_buffer + sections[i].VirtualAddress, sections[i].Misc.VirtualSize, protection, &old);\n"
    "    }\n"
    "\n"
    "    if (g_is_dll) {\n"
    "        typedef BOOL (WINABI *fDllMain)(HINSTANCE, DWORD, LPVOID);\n"
    "        fDllMain dll_main = (fDllMain)((char*)pe_buffer + g_entry_point_rva);\n"
    "#ifdef _WIN64\n"
    "        call_aligned((PVOID)dll_main, (PVOID)pe_buffer, (PVOID)DLL_PROCESS_ATTACH, NULL, NULL);\n"
    "#else\n"
    "        dll_main((HINSTANCE)pe_buffer, DLL_PROCESS_ATTACH, NULL);\n"
    "#endif\n"
    "    } else {\n"
    "        typedef void (*fExeEntry)();\n"
    "        fExeEntry exe_entry = (fExeEntry)((char*)pe_buffer + g_entry_point_rva);\n"
    "#ifdef _WIN64\n"
    "        call_aligned((PVOID)exe_entry, NULL, NULL, NULL, NULL);\n"
    "#else\n"
    "        exe_entry();\n"
    "#endif\n"
    "    }\n"
    "}\n"
    "\n"
    "int main() {\n"
    "    load_pe();\n"
    "\n"
    "    HMODULE h_kernel32 = get_module_handle_manual(\"kernel32.dll\");\n"
    "    HMODULE h_ntdll = get_module_handle_manual(\"ntdll.dll\");\n"
    "    fRtlInitAnsiString _RtlInitAnsiString = (fRtlInitAnsiString)get_export_address_manual(h_ntdll, \"RtlInitAnsiString\", NULL, NULL, NULL, NULL, NULL);\n"
    "    fLdrGetProcedureAddress _LdrGetProcedureAddress = (fLdrGetProcedureAddress)get_export_address_manual(h_ntdll, \"LdrGetProcedureAddress\", _RtlInitAnsiString, NULL, NULL, NULL, NULL);\n"
    "    fGetStdHandle _GetStdHandle = (fGetStdHandle)get_export_address_manual(h_kernel32, \"GetStdHandle\", _RtlInitAnsiString, _LdrGetProcedureAddress, NULL, NULL, NULL);\n"
    "    fWriteFile _WriteFile = (fWriteFile)get_export_address_manual(h_kernel32, \"WriteFile\", _RtlInitAnsiString, _LdrGetProcedureAddress, NULL, NULL, NULL);\n"
    "    fReadFile _ReadFile = (fReadFile)get_export_address_manual(h_kernel32, \"ReadFile\", _RtlInitAnsiString, _LdrGetProcedureAddress, NULL, NULL, NULL);\n"
    "\n"
    "    if (_GetStdHandle && _WriteFile && _ReadFile) {\n"
    "        HANDLE hOut = _GetStdHandle(STD_OUTPUT_HANDLE);\n"
    "        const char msg[] = \"Press Enter to exit...\";\n"
    "        DWORD written;\n"
    "        _WriteFile(hOut, (LPVOID)msg, (DWORD)sizeof(msg)-1, &written, NULL);\n"
    "\n"
    "        HANDLE hIn = _GetStdHandle(STD_INPUT_HANDLE);\n"
    "        char buf[2];\n"
    "        DWORD read;\n"
    "        _ReadFile(hIn, buf, 1, &read, NULL);\n"
    "    }\n"
    "\n"
    "    return 0;\n"
    "}\n";

void print_hex_array(FILE* out, const uint8_t* data, size_t size) {
    fprintf(out, "unsigned char pe_blob[] = {");
    for (size_t i = 0; i < size; i++) {
        if (i % 12 == 0) fprintf(out, "\n    ");
        fprintf(out, "0x%02X%s", data[i], (i == size - 1) ? "" : ", ");
    }
    fprintf(out, "\n};\n");
}

int main(int argc, char* argv[]) {
    if (argc < 2) {
        printf("Usage: %s <payload.exe> [loader_template.c]\n", (argc > 0) ? argv[0] : "exe_to_embedded_loader");
        return 1;
    }

    const char* payload_path = argv[1];
    const char* template_path = (argc > 2) ? argv[2] : "loader_template.c";

    FILE* fp = fopen(payload_path, "rb");
    if (!fp) { perror("Error opening payload"); return 1; }
    fseek(fp, 0, SEEK_END);
    size_t file_size = ftell(fp);
    fseek(fp, 0, SEEK_SET);
    uint8_t* file_data = (uint8_t*)malloc(file_size);
    fread(file_data, 1, file_size, fp);
    fclose(fp);

    IMAGE_DOS_HEADER* dos_header = (IMAGE_DOS_HEADER*)file_data;
    if (dos_header->e_magic != 0x5A4D) { printf("Invalid PE file\n"); return 1; }
    IMAGE_NT_HEADERS64* nt_headers = (IMAGE_NT_HEADERS64*)(file_data + dos_header->e_lfanew);
    DWORD entry_point_rva = nt_headers->OptionalHeader.AddressOfEntryPoint;
    ULONG_PTR image_base = nt_headers->OptionalHeader.ImageBase;
    DWORD size_of_image = nt_headers->OptionalHeader.SizeOfImage;

    char* template_data = NULL;
    FILE* t_fp = fopen(template_path, "r");
    if (t_fp) {
        fseek(t_fp, 0, SEEK_END);
        size_t t_size = ftell(t_fp);
        fseek(t_fp, 0, SEEK_SET);
        template_data = (char*)malloc(t_size + 1);
        fread(template_data, 1, t_size, t_fp);
        template_data[t_size] = '\0';
        fclose(t_fp);
    } else {
        template_data = strdup(default_template);
    }

    FILE* out_fp = fopen("final_loader.c", "w");
    if (!out_fp) { perror("Error opening final_loader.c"); return 1; }

    char* p = template_data;
    while (*p) {
        if (strncmp(p, "// PE_BLOB_ARRAY", 16) == 0) {
            print_hex_array(out_fp, file_data, file_size);
            p = strchr(p, '\n'); if (p) p++;
            p = strchr(p, '\n'); if (p) p++;
        } else if (strncmp(p, "// ENTRY_POINT_RVA", 18) == 0) {
            fprintf(out_fp, "// ENTRY_POINT_RVA\nDWORD entry_point_rva = 0x%X;\n", entry_point_rva);
            p = strchr(p, '\n'); if (p) p++;
            p = strchr(p, '\n'); if (p) p++;
        } else if (strncmp(p, "// IMAGE_BASE", 13) == 0) {
            fprintf(out_fp, "// IMAGE_BASE\nULONG_PTR image_base = 0x%llX;\n", (unsigned long long)image_base);
            p = strchr(p, '\n'); if (p) p++;
            p = strchr(p, '\n'); if (p) p++;
        } else if (strncmp(p, "// SIZE_OF_IMAGE", 16) == 0) {
            fprintf(out_fp, "// SIZE_OF_IMAGE\nSIZE_T size_of_image = 0x%X;\n", size_of_image);
            p = strchr(p, '\n'); if (p) p++;
            p = strchr(p, '\n'); if (p) p++;
        } else {
            fputc(*p++, out_fp);
        }
    }

    fclose(out_fp);
    free(file_data); free(template_data);
    printf("Generated final_loader.c successfully.\n");
    return 0;
}
